version: '3.8'

services:
  web:
    image: kaymima/django-devops-app:latest
    restart: always
    environment:
      - DEBUG=0
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

  # docker-compose.prod.yml
  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Only HTTP
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
