name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/django-devops-app:latest

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@main
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: ${{ secrets.DO_SSH_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            docker-compose -f docker-compose.prod.yml down
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/django-devops-app:latest
            docker-compose -f docker-compose.prod.yml up -d